server:
  port: 8086
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #服务名小写
          lowerCaseServiceId: true
      routes:
        - id: nameRoot
          uri: lb://spring-cloud-producer
          predicates:
          - Path=/name/**
          filters:
          - StripPrefix=1
  redis:
    host: 192.168.241.20
    port: 6379



logging:
  level:
    org.springframework.cloud.gateway: debug
