server:
  port: 8082
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.1.114:3310/lhjc_zsnew?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: lhjczsdbuser
    password: LhjcZsDbUser@20181106!
  rabbitmq:
    host: 192.168.241.20
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
    
data:
  env: web-dev1
