server:
  port: 8082
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
        
feign:
  hystrix:
    enabled: true

mybatis:
  type-aliases-package: com.neo.entity
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.1.114:3310/lhjc_zsnew?characterEncoding=utf8&useSSL=true&verifyServerCertificate=false
    username: lhjczsdbuser
    password: LhjcZsDbUser@20181106!
    
data:
  env: web-dev
