server:
  port: 8084

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
spring:
  rabbitmq:
    host: 192.168.241.20
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
