server:
  port: 8084

feign:
  hystrix:
    enabled: true
    
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
        
spring:
  rabbitmq:
    host: 192.168.241.20
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
  zipkin:
    base-url: http://192.168.241.20:9411/
  sleuth:
    sampler:
      probability: 1.0
