server:
  port: 8083
  
zuul:
  ignored-services: someapp
  routes:
    webapp: /zuultest/**

spring:
  rabbitmq:
    host: 192.168.241.20
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
